FROM python:3.10-slim

WORKDIR /app

COPY actions/ ./actions/
COPY requirements-actions.txt .

RUN pip install -r requirements-actions.txt

CMD ["python", "-m", "rasa_sdk", "--actions", "actions", "--port", "5055"]